services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - serveur
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - WATCHPACK_POLLING=true  # Enable polling for Windows compatibility
      - CHOKIDAR_USEPOLLING=true  # Enable polling for hot reload
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=3000
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules

  serveur:
    build:
      context: .
      dockerfile: serveur/Dockerfile
    ports:
      - "5000:5000"
      - "9229:9229"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=host.docker.internal
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - SERVER_PORT=5000
      - CHOKIDAR_USEPOLLING=true  
      - NODE_ENV=development
    networks:
      - app-network
    volumes:
      - ./serveur:/app
      - ./serveur_calcul_python:/app/serveur_calcul_python
      - /app/node_modules
    command: npm run dev 

volumes:
  client_node_modules:
networks:
  app-network:
    driver: bridge