services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - WATCHPACK_POLLING=true  # Enable polling for Windows compatibility
      - CHOKIDAR_USEPOLLING=true  # Enable polling for hot reload
      - FAST_REFRESH=true
      - WDS_SOCKET_PORT=3000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "9229:9229"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=host.docker.internal
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - SERVER_PORT=5000
      - CHOKIDAR_USEPOLLING=true  
      - NODE_ENV=development
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev 


volumes:
  frontend_node_modules:
networks:
  app-network:
    driver: bridge