FROM continuumio/miniconda3

WORKDIR /app

RUN apt-get update && apt-get install -y ca-certificates

COPY environment.yml .

# Create Conda environment and activate it

#RUN conda config --set ssl_verify false
#RUN conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
#RUN conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
RUN conda config --set show_channel_urls yes


# Mettre à jour Conda et configurer les canaux
RUN conda update -n base -c defaults conda
RUN conda config --add channels conda-forge

RUN conda env create -f environment.yml
SHELL ["conda", "run", "-n", "serveur_calcul_python", "/bin/bash", "-c"]

COPY . .

CMD ["conda", "run", "-n", "serveur_calcul_python", "python3"]